---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maven
  name: maven
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - image: duniaalk/kaniko-maven:10
        imagePullPolicy: Always
        name: maven

---
apiVersion: v1
kind: Service
metadata:
  name: maven
spec:
  selector:
    app: maven
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
    nodePort: 30000

